# Trinity Platform - Container Apps YAML Manifest
# Alternative to Bicep for declarative deployment

# Event Collector
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-collector
spec:
  replicas: 2
  selector:
    matchLabels:
      app: event-collector
  template:
    metadata:
      labels:
        app: event-collector
    spec:
      containers:
      - name: event-collector
        image: trinityacr.azurecr.io/event-collector:latest
        ports:
        - containerPort: 8000
        env:
        - name: SERVICEBUS_CONNECTION
          valueFrom:
            secretKeyRef:
              name: trinity-secrets
              key: servicebus-connection
        - name: POSTGRES_URL
          valueFrom:
            secretKeyRef:
              name: trinity-secrets
              key: postgres-url
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5

---
# RCA API
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rca-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rca-api
  template:
    metadata:
      labels:
        app: rca-api
    spec:
      containers:
      - name: rca-api
        image: trinityacr.azurecr.io/rca-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: COSMOS_CONNECTION
          valueFrom:
            secretKeyRef:
              name: trinity-secrets
              key: cosmos-connection
        - name: VECTOR_SEARCH_URL
          value: "http://vector-search:8000"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"

---
# Vector Search
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vector-search
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vector-search
  template:
    metadata:
      labels:
        app: vector-search
    spec:
      containers:
      - name: vector-search
        image: trinityacr.azurecr.io/vector-search:latest
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: trinity-secrets
              key: redis-host
        - name: REDIS_KEY
          valueFrom:
            secretKeyRef:
              name: trinity-secrets
              key: redis-key
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"

---
# API Gateway
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: trinityacr.azurecr.io/api-gateway:latest
        ports:
        - containerPort: 8000
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: trinity-secrets
              key: jwt-secret
        - name: USER_MGMT_URL
          value: "http://user-management:8000"
        - name: RCA_API_URL
          value: "http://rca-api:8000"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"

---
# Service (LoadBalancer for API Gateway)
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  type: LoadBalancer
  ports:
  - port: 443
    targetPort: 8000
    protocol: TCP
  selector:
    app: api-gateway
